#!/usr/bin/env python3
"""Generate the full-kit DVT snapshot using pinned source packages, without ROS.

Clone repositories in description-lock.json into --deps-root and checkout their
recorded commits first. Requires Python and PyYAML. Live ROS launch continues to
expand Xacro using installed packages and the robot's own configuration.
"""

import argparse
import json
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def generate(core, deps, gazebo=False):
    lock = json.loads((core / "tools/description-lock.json").read_text())
    for name, spec in lock["repositories"].items():
        repo = deps / name
        sha = subprocess.check_output(
            ["git", "-C", str(repo), "rev-parse", "HEAD"], text=True
        ).strip()
        dirty = subprocess.check_output(
            ["git", "-C", str(repo), "status", "--porcelain", "--untracked-files=no"],
            text=True,
        )
        if sha != spec["commit"] or dirty:
            raise RuntimeError(f"{name}: expected clean {spec['commit']}, got {sha}")
    sys.path.insert(0, str(deps / "xacro"))
    import xacro
    import xacro.substitution_args

    packages = {
        "reachy_description": core / "reachy_description",
        "reachy_bringup": core / "reachy_bringup",
        "dynamixel_description": core
        / "reachy_controllers/dynamixel_control/dynamixel_description",
        "orbita2d_description": deps / "orbita2d_control/orbita2d_description",
        "orbita3d_description": deps / "orbita3d_control/orbita3d_description",
        "pollen_generic_description": deps
        / "ros2_pollen_toolbox/pollen_generic_description",
        "zuuu_description": deps / "mobile_base/zuuu_description",
    }
    # Pinned Xacro's package resolver: only package lookup is replaced, not macro evaluation.
    previous = xacro.substitution_args._eval_find
    xacro.substitution_args._eval_find = lambda name: str(packages[name])
    arguments = dict(lock["arguments"])
    if gazebo:
        arguments["use_gazebo"] = "true"
    try:
        doc = xacro.process_file(
            str(core / "reachy_description/urdf/reachy.urdf.xacro"), mappings=arguments
        )
    finally:
        xacro.substitution_args._eval_find = previous
    text = doc.toxml()
    for name, path in sorted(packages.items(), key=lambda item: -len(str(item[1]))):
        text = text.replace("file://" + str(path) + "/", "package://" + name + "/")
        # Control config filenames are deployment-specific. The checked snapshot is
        # for geometry consumers; its control paths use a deterministic install prefix.
        text = text.replace(
            str(path) + "/", "/opt/reachy-description/share/" + name + "/"
        )
    root = ET.fromstring(text)
    ET.indent(root, space="  ")
    return (
        '<?xml version="1.0"?>\n<!-- Generated by tools/generate_description.py; see tools/description-lock.json. -->\n'
        + ET.tostring(root, encoding="unicode")
        + "\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--deps-root", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--gazebo",
        action="store_true",
        help="Generate a temporary Gazebo validation variant",
    )
    parser.add_argument(
        "--check", action="store_true", help="Check the snapshot without writing"
    )
    args = parser.parse_args()
    core = Path(__file__).resolve().parents[1]
    output = args.output or core / "reachy_description/urdf/reachy2.urdf"
    if args.gazebo and not args.output:
        parser.error(
            "--gazebo requires --output; the checked snapshot is not a Gazebo model"
        )
    result = generate(core, args.deps_root.resolve(), args.gazebo)
    if args.check:
        if output.read_text() != result:
            raise SystemExit(f"Generated description differs from {output}")
    else:
        output.write_text(result)
    print(f"{'Verified' if args.check else 'Generated'} {output}")


if __name__ == "__main__":
    main()
